name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there :wave: Thank you for opening a new issue :sparkles: \nYour issue will be reviewed and assigned soon :hourglass:\nHappy Coding :smiley:'' first issue'
        pr-message: 'Hi there :wave: Congratulations on sending your first PR :sparkles: \nYour PR will be reviewed soon :hourglass:\nHappy Coding :smiley:'' first pr'
